### PR TITLE
Fix extra cuboid downloads

### PR DESCRIPTION
**Pull request by j6k4m8**
...i'm ashamed

### CODE REVIEW

**Comment by j6k4m8** [comment]
Nope, that wasn't it. Actually.... @movestill — i'm having a hard time getting the same results; i THINK it's just downloading what it needs..?

**Comment by movestill** [comment]
If I took an empty cache and downloaded less than a cuboid, say 0:128, 0:128, 0:16, I'm pretty sure I saw an extra cuboid in the positive direction along each axis.

I'll try again later. I haven't been able to get myself to do any Rust after hours. Django upgrades having been crushing my soul!

**Review by movestill — APPROVED** [review]

**Comment by movestill** [comment]
I almost couldn't remember the `cargo run` command today! :grin:

Looks like rocket isn't building in CI now, though. 😢  Think something changed with the nightly Rust build. CI is configured to use the latest nightly build.

**Comment by j6k4m8** [comment]
Yes! Just found out rocket is going to (already does?) work on `stable` so
we can probably increment our rust version dep and remove the nightly
requirement!!

**Comment by movestill** [comment]
Nice, it’ll be good to switch to stable. IIRC correctly, it was something with macros that required nightly? Need to see if diesel requires nightly. It does some fancy stuff with macros, too.

**Pull request merged**
